export const CLOUDINARY_CONFIG = {
  CLOUD_NAME: import.meta.env.VITE_CLOUD_NAME,
  UPLOAD_PRESET: import.meta.env.VITE_CLOUDINARY_UPLOAD_PRESET,
  UPLOAD_URL: import.meta.env.VITE_CLOUDINARY_UPLOAD_URL
}
